name:           Entry CSV Export
description:    Export full-fidelity entry/page metadata in CSV format from the entry/page listing screen
version:        1.1.0
author_name:    Endevver, LLC
author_link:    http://endevver.com
id:             EntryCSVExport
key:            EntryCSVExport

list_actions:
  entry:
    csv_export:
      label: Export as CSV
      order: 1000
      handler: $EntryCSVExport::EntryCSVExport::CMS::entry_csv_export
  page:
    csv_export:
      label: Export as CSV
      order: 1000
      handler: $EntryCSVExport::EntryCSVExport::CMS::entry_csv_export

page_actions:
   list_entry:
       export_entries_csv:
           label: Export all entries (CSV)
           order: 101
           code:  $EntryCSVExport::EntryCSVExport::CMS::entry_csv_export
           permission: edit_all_posts
           condition: $EntryCSVExport::EntryCSVExport::CMS::is_system_context
       export_blog_entries_csv:
           label: "Export this blog's entries (CSV)"
           order: 101
           code:  $EntryCSVExport::EntryCSVExport::CMS::entry_csv_export
           permission: edit_all_posts
           condition: $EntryCSVExport::EntryCSVExport::CMS::is_blog_context
   list_pages:
       export_pages_csv:
           label: Export all pages (CSV)
           order: 101
           code:  $EntryCSVExport::EntryCSVExport::CMS::entry_csv_export
           permission: edit_all_posts
           condition: $EntryCSVExport::EntryCSVExport::CMS::is_system_context
       export_blog_pages_csv:
           label: "Export this blog's pages (CSV)"
           order: 101
           code:  $EntryCSVExport::EntryCSVExport::CMS::entry_csv_export
           permission: edit_all_posts
           condition: $EntryCSVExport::EntryCSVExport::CMS::is_blog_context
